### ISSUE TITLE
mapserver with apache24 and mode=map serves a broken image

### ISSUE THREAD

**Issue by amr66** [gisinternals/buildsystem#193] opened 2022-03-17 11:56 UTC
I run gisinternals mapserver with an Apache24 under win10. When I request a map with a html template and mode=browse everything works fine but if I try to use mode=map I get an error in my browser (Firefox): 'Die Grafik "http://localhost:8008/ms-bin/mapserv.exe?map=/gims/mapserver/test/regio_tr.map&mode=map" kann nicht angezeigt werden, weil sie Fehler enthält.' (The Image ... can't be displayed, because it contains errors). I don't see any errors in the Apache log files nor in the mapserver debug logs. I'm not completly sure if this error belongs to mapserver or to the apache config.

**Comment by szekerest** [comment] 2022-03-17 12:20
@amr66 Could you download the resulting image and attach that to this ticket?

**Comment by amr66** [comment] 2022-03-17 13:23
@szekerest thank you, here it is: 
![mapserv exe](https://user-images.githubusercontent.com/10866105/158817477-e0a2c3e7-bdd2-4aa8-99a7-dd8d5f11ceb9.png)

**Comment by szekerest** [comment] 2022-03-17 16:48
@amr66 pngcheck says that the file is corrupted by text conversion. I'm not sure however it was happened during the png creation or when it was saved to the file. Could you provide some test data to reproduce this problem? 
If you open a gisinternals command prompt and run mapserv from the command line, does it provied correct result? Something like:

`mapserv -nh "QUERY_STRING=map=/gims/mapserver/test/regio_tr.map&mode=map" > sample.png`

**Comment by amr66** [comment] 2022-03-17 17:05
@szekerest sure, this is the output file:
![sample](https://user-images.githubusercontent.com/10866105/158854716-6398bc36-dd1e-4d02-a5c6-99ff60492b44.png)

**Comment by amr66** [comment] 2022-03-18 15:10
Another simple example is the "Hello World"-map file, ignore the template, it is called with mode=map of course 
```
MAP
   NAME HELLO 
   STATUS ON 
   EXTENT 0 0 4000 3000 
   SIZE 400 300 
   IMAGECOLOR 180 60 255 
WEB
   IMAGEPATH "/gims/test/ms_tmp/" 
   IMAGEURL "/test/ms_tmp/" 
   TEMPLATE "/gims/test/hw.htm"
END 
LAYER
     STATUS default
     TYPE point
     FEATURE
          POINTS  2000.00 1500.00 END
          TEXT "Hello World. Mapserver rocks."
     END # end feature
     CLASS
          STYLE
               COLOR 255 0 0
          END
          LABEL
               TYPE bitmap
          END
     END
END 
END
```

**Comment by amr66** [comment] 2022-03-18 16:12
Good Idea! 
```
OUTPUTFORMAT
  NAME "jpeg"
  DRIVER AGG/JPEG
  MIMETYPE "image/jpeg"
  IMAGEMODE RGB
  EXTENSION "jpg"
END
```
It shows the image, but it looks weird
![mapserv exe](https://user-images.githubusercontent.com/10866105/159040617-fc973570-92a2-4ab6-95e7-d0d239b66a5d.jpg)
.

**Comment by szekerest** [comment] 2022-03-18 16:33
Checked the wrong output and it seems that the stdout is not being switched to binary mode so extra 0x0D bytes are inserted into the image. Looks like we need to patch libfcgi to get it working as per:
https://github.com/MapServer/MapServer/issues/1153

I'll apply that fix and trigger a new build with that.

**Comment by amr66** [comment] 2022-03-18 17:29
I can confirm, that replacing libfcgi.dll from an osgeo4w install with same 64-bit MSVC 2019 (in my case) works.

**Comment by geographika** [comment] 2022-03-18 18:26
@szekerest - could this also be the cause of https://github.com/MapServer/MapServer/issues/6459 ?

**Comment by szekerest** [comment] 2022-03-18 19:44
@geographika yes, definitely

**Comment by szekerest** [comment] 2022-03-18 20:14
Recompiled the release versions 
https://www.gisinternals.com/release.php
It seems that the problem was fixed.

**Comment by amr66** [comment] 2022-03-19 12:55
Thank you for your quick fix. It works!

**Comment by szekerest** [comment] 2022-03-19 16:48
Thank you, closing this

**Closed by szekerest** 2022-03-19 16:48 UTC
